SQLTYPECODE_CHAR = 1
# NUMERIC * /
SQLTYPECODE_NUMERIC = 2
SQLTYPECODE_NUMERIC_UNSIGNED = -201
# DECIMAL * /
SQLTYPECODE_DECIMAL = 3
SQLTYPECODE_DECIMAL_UNSIGNED = -301
SQLTYPECODE_DECIMAL_LARGE = -302
SQLTYPECODE_DECIMAL_LARGE_UNSIGNED = -303
# INTEGER / INT * /
SQLTYPECODE_INTEGER = 4
SQLTYPECODE_INTEGER_UNSIGNED = -401
SQLTYPECODE_LARGEINT = -402
SQLTYPECODE_LARGEINT_UNSIGNED = -405
# SMALLINT
SQLTYPECODE_SMALLINT = 5
SQLTYPECODE_SMALLINT_UNSIGNED = -502
SQLTYPECODE_BPINT_UNSIGNED = -503

    # TINYINT */
SQLTYPECODE_TINYINT                = -403
SQLTYPECODE_TINYINT_UNSIGNED       = -404

# DOUBLE depending on precision
SQLTYPECODE_FLOAT = 6
SQLTYPECODE_REAL = 7
SQLTYPECODE_DOUBLE = 8

# DATE,TIME,TIMESTAMP */
SQLTYPECODE_DATETIME = 9

# TIMESTAMP */
SQLTYPECODE_INTERVAL = 10

# no ANSI value 11 */

# VARCHAR/CHARACTER VARYING */
SQLTYPECODE_VARCHAR = 12
# SQL/MP stype VARCHAR with length prefix:
SQLTYPECODE_VARCHAR_WITH_LENGTH = -601
SQLTYPECODE_BLOB = -602
SQLTYPECODE_CLOB = -603
# LONG VARCHAR/ODBC CHARACTER VARYING */
SQLTYPECODE_VARCHAR_LONG = -1 # ## NEGATIVE??? */

# no ANSI value 13 */

# BIT */
SQLTYPECODE_BIT = 14 # not supported */

# BIT VARYING */
SQLTYPECODE_BITVAR = 15 # not supported */

# NCHAR -- CHAR(n) CHARACTER SET s -- where s uses two bytes per char */
SQLTYPECODE_CHAR_DBLBYTE = 16
# NCHAR VARYING -- VARCHAR(n) CHARACTER SET s -- s uses 2 bytes per char */
SQLTYPECODE_VARCHAR_DBLBYTE = 17
# BOOLEAN TYPE */
SQLTYPECODE_BOOLEAN = -701

# Date/Time/TimeStamp related constants */
SQLDTCODE_DATE = 1
SQLDTCODE_TIME = 2
SQLDTCODE_TIMESTAMP = 3
SQLDTCODE_MPDATETIME = 4